// <auto-generated />
using System;
using GestionAgenda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionAgenda.Migrations
{
    [DbContext(typeof(ContextBd))]
    [Migration("20251128142948_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionAgenda.Modelo.Archivo", b =>
                {
                    b.Property<int>("id_archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_archivo"));

                    b.Property<int>("citaid_cita")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idCita")
                        .HasColumnType("int");

                    b.Property<string>("nombreARchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipoArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_archivo");

                    b.HasIndex("citaid_cita");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Cita", b =>
                {
                    b.Property<int>("id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_cita"));

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fechaAgendado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaRealizada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("hcid_hc")
                        .HasColumnType("int");

                    b.Property<int>("idHistorialClinico")
                        .HasColumnType("int");

                    b.Property<int>("idProfesional")
                        .HasColumnType("int");

                    b.Property<string>("profesionalusuario_profesional")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_cita");

                    b.HasIndex("hcid_hc");

                    b.HasIndex("profesionalusuario_profesional");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.HistorialClinico", b =>
                {
                    b.Property<int>("id_hc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_hc"));

                    b.HasKey("id_hc");

                    b.ToTable("Historiales");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Paciente", b =>
                {
                    b.Property<int>("id_paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_paciente"));

                    b.Property<string>("contrasenia_paciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("historial_clinicoid_hc")
                        .HasColumnType("int");

                    b.Property<string>("nombre_completo_paciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("usuario_paciente")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_paciente");

                    b.HasIndex("historial_clinicoid_hc")
                        .IsUnique();

                    b.HasIndex("usuario_paciente")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Profesional", b =>
                {
                    b.Property<string>("usuario_profesional")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("contrasenia_profesional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre_completo_profesional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("profesion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("usuario_profesional");

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Recordatorio", b =>
                {
                    b.Property<int>("id_recordatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_recordatorio"));

                    b.Property<DateTime>("fechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pacienteid_paciente")
                        .HasColumnType("int");

                    b.Property<string>("profesionalusuario_profesional")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_recordatorio");

                    b.HasIndex("pacienteid_paciente");

                    b.HasIndex("profesionalusuario_profesional");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Archivo", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("citaid_cita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Cita", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.HistorialClinico", "hc")
                        .WithMany("citas")
                        .HasForeignKey("hcid_hc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionAgenda.Modelo.Profesional", "profesional")
                        .WithMany()
                        .HasForeignKey("profesionalusuario_profesional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hc");

                    b.Navigation("profesional");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Paciente", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.HistorialClinico", "historial_clinico")
                        .WithOne()
                        .HasForeignKey("GestionAgenda.Modelo.Paciente", "historial_clinicoid_hc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("historial_clinico");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Recordatorio", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionAgenda.Modelo.Profesional", "profesional")
                        .WithMany()
                        .HasForeignKey("profesionalusuario_profesional");

                    b.Navigation("paciente");

                    b.Navigation("profesional");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.HistorialClinico", b =>
                {
                    b.Navigation("citas");
                });
#pragma warning restore 612, 618
        }
    }
}
