// <auto-generated />
using System;
using GestionAgenda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionAgenda.Migrations
{
    [DbContext(typeof(ContextBd))]
    partial class ContextBdModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionAgenda.Modelo.Archivo", b =>
                {
                    b.Property<int>("id_archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_archivo"));

                    b.Property<int>("citaid_cita")
                        .HasColumnType("int");

                    b.Property<string>("rutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_archivo");

                    b.HasIndex("citaid_cita");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Cita", b =>
                {
                    b.Property<int>("id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cita"));

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaAgendado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<int>("hcid_hc")
                        .HasColumnType("int");

                    b.Property<string>("profesionalusuario_profesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id_cita");

                    b.HasIndex("hcid_hc");

                    b.HasIndex("profesionalusuario_profesional");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.HistorialClinico", b =>
                {
                    b.Property<int>("id_hc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_hc"));

                    b.Property<string>("pacienteusuario_paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id_hc");

                    b.HasIndex("pacienteusuario_paciente");

                    b.ToTable("Historiales");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Paciente", b =>
                {
                    b.Property<string>("usuario_paciente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contrasenia_paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_completo_paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuario_paciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Profesional", b =>
                {
                    b.Property<string>("usuario_profesional")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contrasenia_profesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_completo_profesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuario_profesional");

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Recordatorio", b =>
                {
                    b.Property<int>("id_recordatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_recordatorio"));

                    b.Property<DateTime>("fechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pacienteusuario_paciente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("profesionalusuario_profesional")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id_recordatorio");

                    b.HasIndex("pacienteusuario_paciente");

                    b.HasIndex("profesionalusuario_profesional");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Telefono", b =>
                {
                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pacienteusuario_paciente")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("numero");

                    b.HasIndex("Pacienteusuario_paciente");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Archivo", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("citaid_cita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Cita", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.HistorialClinico", "hc")
                        .WithMany()
                        .HasForeignKey("hcid_hc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionAgenda.Modelo.Profesional", "profesional")
                        .WithMany()
                        .HasForeignKey("profesionalusuario_profesional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hc");

                    b.Navigation("profesional");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.HistorialClinico", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteusuario_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Recordatorio", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteusuario_paciente");

                    b.HasOne("GestionAgenda.Modelo.Profesional", "profesional")
                        .WithMany()
                        .HasForeignKey("profesionalusuario_profesional");

                    b.Navigation("paciente");

                    b.Navigation("profesional");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Telefono", b =>
                {
                    b.HasOne("GestionAgenda.Modelo.Paciente", null)
                        .WithMany("telefonos")
                        .HasForeignKey("Pacienteusuario_paciente");
                });

            modelBuilder.Entity("GestionAgenda.Modelo.Paciente", b =>
                {
                    b.Navigation("telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
